# Generated by Django 4.1.dev20220304115537 on 2022-04-02 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstName", models.CharField(max_length=150)),
                ("lastName", models.CharField(max_length=150)),
                ("age", models.PositiveIntegerField()),
                (
                    "priority",
                    models.CharField(
                        choices=[("1", "Emergency"), ("2", "Admit"), ("3", "Normal")],
                        default="1",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
